spring.application.name=demo-api
server.port=8080
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
app.base-url=http://localhost:8080
